name: Build and Update Manifest

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV    

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nkdeveloper26/myrecipe-frontend:${{ env.VERSION }}
            nkdeveloper26/myrecipe-frontend:latest

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Manifest repo
        uses: actions/checkout@v4
        with:
          repository: nkserveren26/recipe_k8s_yaml
          path: manifest
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Update Deployment manifest
        run: |
          sed -i "s#image: nkdeveloper26/myrecipe-frontend:.*#image: nkdeveloper26/myrecipe-frontend:${VERSION}#g" manifest/frontend/deployment.yaml
